### ISSUE TITLE
push an update of code to users

### ISSUE THREAD

**Issue by TeroFrondelius** [supasorn/GoogleScholarCopyBibTeX#4]
Hi,
I just installed the extension and unfortunately latest commit https://github.com/supasorn/GoogleScholarCopyBibTeX/commit/32a8f32070214f6fbfd14a136bf17caa03620de6 is not included. You might want to consider publishing a new version. See instructions:
https://developer.chrome.com/webstore/faq#faq-dev-02

**Comment by supasorn** [comment]
Thanks for reminding! I just did.

**Comment by TeroFrondelius** [comment]
Thanks.
